import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve, sep } from 'node:path';
import { SLUG_RE } from './slug.js';

const run = promisify(execFile);

export interface CreatePrOptions {
  cwd: string;
  /** Already-slugified identifier (validated again here, defensively). */
  slug: string;
  title: string;
  markdown: string;
  baseBranch?: string;
}

export interface PrResult {
  ok: boolean;
  url?: string;
  reason?: string;
}

const IMPROVEMENTS_DIR = 'improvements';

/**
 * Open a PR containing exactly one markdown file (`improvements/<slug>.md`).
 *
 * The "markdown-only, never code" guarantee is structural, not advisory:
 *  - filenames and branch names derive solely from a regex-validated slug;
 *  - the file is the only thing written to disk;
 *  - staging is a single explicit path (`git add improvements/<slug>.md`),
 *    never `git add -A`/`.`;
 *  - the staged set is asserted to be exactly that one path before committing.
 * The model only ever influences the file's *contents* and the PR title.
 */
export async function createImprovementPr(opts: CreatePrOptions): Promise<PrResult> {
  const { cwd, slug, title, markdown } = opts;
  const baseBranch = opts.baseBranch ?? 'main';

  // Defense in depth: never trust the caller's slug.
  if (!SLUG_RE.test(slug)) {
    return { ok: false, reason: `Refusing unsafe slug: ${slug}` };
  }

  const relPath = `${IMPROVEMENTS_DIR}/${slug}.md`;
  const dirAbs = join(cwd, IMPROVEMENTS_DIR);
  const fileAbs = join(dirAbs, `${slug}.md`);
  // Path-traversal guard (redundant with SLUG_RE, kept as a hard boundary).
  if (resolve(fileAbs) !== fileAbs || !fileAbs.startsWith(dirAbs + sep)) {
    return { ok: false, reason: 'Resolved path escaped the improvements directory.' };
  }

  const branch = `improve/${slug}`;

  // --- Preflight: fail gracefully rather than throw into the exit path. ---
  try {
    await run('gh', ['--version'], { cwd });
  } catch {
    return { ok: false, reason: 'gh CLI not found — install and authenticate it to open improvement PRs.' };
  }
  try {
    await run('git', ['rev-parse', '--is-inside-work-tree'], { cwd });
  } catch {
    return { ok: false, reason: 'Not inside a git repository.' };
  }
  try {
    await run('gh', ['auth', 'status'], { cwd });
  } catch {
    return { ok: false, reason: 'gh CLI is not authenticated (run `gh auth login`).' };
  }

  const dirty = (await run('git', ['status', '--porcelain'], { cwd })).stdout.trim();
  if (dirty.length > 0) {
    return {
      ok: false,
      reason: 'Working tree has uncommitted changes — commit or stash them before proposing an improvement.',
    };
  }

  const original = (await run('git', ['rev-parse', '--abbrev-ref', 'HEAD'], { cwd })).stdout.trim();

  try {
    await run('git', ['checkout', '-b', branch], { cwd });

    mkdirSync(dirAbs, { recursive: true });
    writeFileSync(fileAbs, markdown.endsWith('\n') ? markdown : `${markdown}\n`);

    // The single, explicit staged path — never `git add -A`/`.`.
    await run('git', ['add', relPath], { cwd });

    // Belt-and-suspenders: confirm nothing else got staged.
    const staged = (await run('git', ['diff', '--cached', '--name-only'], { cwd })).stdout
      .split('\n')
      .map((s) => s.trim())
      .filter(Boolean);
    if (staged.length !== 1 || staged[0] !== relPath) {
      throw new Error(`Unexpected staged files: ${staged.join(', ') || '(none)'}`);
    }

    await run('git', ['commit', '-m', `docs: propose improvement — ${title}`], { cwd });
    await run('git', ['push', '-u', 'origin', branch], { cwd });

    const body =
      `Automated improvement proposal generated by tiny-code from session usage.\n\n` +
      `This PR intentionally contains a single markdown file under \`${IMPROVEMENTS_DIR}/\` and no code changes — ` +
      `it is for a maintainer to review and implement separately.`;
    const created = await run(
      'gh',
      ['pr', 'create', '--base', baseBranch, '--head', branch, '--title', title, '--body', body],
      { cwd },
    );
    const url = created.stdout.trim().split('\n').filter(Boolean).pop();

    return url ? { ok: true, url } : { ok: true };
  } catch (err) {
    return { ok: false, reason: (err as Error).message };
  } finally {
    // Best-effort restore of the user's original branch.
    try {
      await run('git', ['checkout', original], { cwd });
    } catch {
      /* leave them on the improve branch rather than masking the real result */
    }
  }
}
